# Base image with Python 3.10
FROM python:3.10-slim

# Set the working directory in the container
WORKDIR /backend

# Copy the Python dependencies file to the container
COPY flask-backend/requirements.txt .

# Install any dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy the Flask application to the container
COPY flask-backend/ .

# Copy the .env file
COPY .env .

# Set the FLASK_APP environment variable to point to your app's entry point
ENV FLASK_APP=resources/example_prompt_one.py
ENV FLASK_RUN_HOST=0.0.0.0

# Expose the port the app runs on
EXPOSE 5000

# Command to run the Flask application
CMD ["flask", "run"]
