version: '3'
services:
  backend:
    build:
      context: ./flask-backend
      dockerfile: dockerfile
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production

  frontend:
    build:
      context: ./phillygpt
      dockerfile: dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend