# Dockerfile.backend
FROM python:3.10-slim

WORKDIR /backend

COPY flask-backend/requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY flask-backend/ .

CMD ["flask", "run", "--host=0.0.0.0"]

